=== epam/edp-ddm-liquibase-ddm-ext/src/main/resources/parameters.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    targetNamespace="http://www.liquibase.org/xml/ns/dbchangelog-ext"
    elementFormDefault="qualified">

    <xsd:annotation>
        <xsd:appinfo>MDTU-DDM project</xsd:appinfo>
        <xsd:documentation xml:lang="en">
        </xsd:documentation>
    </xsd:annotation>

    <xsd:simpleType name="scopeTypeOptions">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="all"/>
            <xsd:enumeration value="primary"/>
            <xsd:enumeration value="history"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:element name="parameters">
        <xsd:complexType>
            <xsd:choice>
                <xsd:element name="historyFlag">
                    <xsd:complexType>
                        <xsd:choice minOccurs="0" maxOccurs="unbounded">
                            <xsd:element name="tableSuffix" maxOccurs="1">
                                <xsd:complexType>
                                    <xsd:attribute name="name" type="xsd:string" use="optional"/>
                                </xsd:complexType>
                            </xsd:element>

                            <xsd:element name="subjectTable" maxOccurs="1">
                                <xsd:complexType>
                                    <xsd:attribute name="name" type="xsd:string" use="required"/>
                                    <xsd:attribute name="column" type="xsd:string" use="required"/>
                                    <xsd:attribute name="type" type="xsd:string" use="required"/>
                                </xsd:complexType>
                            </xsd:element>

                            <xsd:element name = "columns" maxOccurs="1">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="column" minOccurs="0" maxOccurs="unbounded">
                                            <xsd:complexType>
                                                <xsd:attribute name="name" type="xsd:string" use="required"/>
                                                <xsd:attribute name="type" type="xsd:string" use="required"/>
                                                <xsd:attribute name="scope" type="scopeTypeOptions" use="optional" default="primary"/>
                                                <xsd:attribute name="uniqueWithPrimaryKey" type="xsd:boolean" use="optional"/>
                                                <xsd:attribute name="nullable" type="xsd:boolean" use="optional"/>
                                                <xsd:attribute name="defaultValueComputed" type="xsd:string" use="optional"/>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>

                            <xsd:element name = "dcmColumns" maxOccurs="1">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="column" minOccurs="0" maxOccurs="unbounded">
                                            <xsd:complexType>
                                                <xsd:attribute name="name" type="xsd:string" use="required"/>
                                                <xsd:attribute name="type" type="xsd:string" use="required"/>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>

                        </xsd:choice>
                    </xsd:complexType>
                </xsd:element>
            </xsd:choice>
        </xsd:complexType>
    </xsd:element>


</xsd:schema>

=== epam/edp-ddm-liquibase-ddm-ext/src/main/resources/parameters.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    uniqueWithPrimaryKey - creates unique constraint with primary key; values- boolean, default - false
    scope - for which table this column is applied; values - all/primary/history, default - all
-->

<ext:parameters
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext parameters.xsd">

    <ext:historyFlag>
        <ext:columns>
            <ext:column name="ddm_created_at"
                type="TIMESTAMPTZ"
                scope="all"
                uniqueWithPrimaryKey="true"
                nullable="false"
                defaultValueComputed="NOW()"/>
            <ext:column name="ddm_created_by"
                type="TEXT"
                scope="all"
                nullable="false"/>
            <ext:column name="ddm_dml_op"
                type="CHAR(1)"
                scope="history"
                nullable="false"/>
            <ext:column name="ddm_updated_at"
                type="TIMESTAMPTZ"
                scope="primary"
                nullable="false"
                defaultValueComputed="NOW()"/>
            <ext:column name="ddm_updated_by"
                type="TEXT"
                scope="primary"
                nullable="false"/>
            <ext:column name="ddm_system_id"
                type="UUID"
                scope="history"
                nullable="false"/>
            <ext:column name="ddm_application_id"
                type="UUID"
                scope="history"
                nullable="false"/>
            <ext:column name="ddm_business_process_id"
                type="UUID"
                scope="history"
                nullable="true"/>
            <ext:column name="ddm_business_process_definition_id"
                type="TEXT"
                scope="history"
                nullable="true"/>
            <ext:column name="ddm_business_process_instance_id"
                type="TEXT"
                scope="history"
                nullable="true"/>
            <ext:column name="ddm_business_activity"
                type="TEXT"
                scope="history"
                nullable="true"/>
            <ext:column name="ddm_business_activity_instance_id"
                type="TEXT"
                scope="history"
                nullable="true"/>
            <ext:column name="ddm_digital_sign"
                type="TEXT"
                scope="history"
                nullable="true"/>
            <ext:column name="ddm_digital_sign_derived"
                type="TEXT"
                scope="history"
                nullable="true"/>
            <ext:column name="ddm_digital_sign_checksum"
                type="TEXT"
                scope="history"
                nullable="true"/>
            <ext:column name="ddm_digital_sign_derived_checksum"
                type="TEXT"
                scope="history"
                nullable="true"/>
        </ext:columns>

        <ext:tableSuffix name="_hst"/>

        <ext:subjectTable name="subject" column="subject_id" type="UUID"/>

        <ext:dcmColumns>
            <ext:column name="dcm_classification" type="type_classification[]"/>
            <ext:column name="dcm_access_role" type="type_access_role[]"/>
        </ext:dcmColumns>

    </ext:historyFlag>
</ext:parameters>
